### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by skrivy** [skyscrapers/puppet-supervisord#3]
Some examples would be great.

**Comment by iuriaranda** [comment]
Sorry @skrivy for not coming back to you earlier. Not sure if this is relevant for you anymore, but I've gone ahead and extended the module's documentation a bit anyway.

I'm going to close this issue for now. If this is still relevant for you and you think the module is still not properly documented feel free to reopen the issue or contribute a PR 🙂

We're making steps towards a more active community participation, so we'll do our best to respond to issues and PRs in a reasonable timeframe from now on.
